'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, MapPin, Waves, Sun, Mountain, Compass, Heart, X, Menu, Leaf, ChevronRight, Download, Check, Signal, Landmark } from 'lucide-react';
type Place = { id: string; title: string; town: string; category: string; image: string; intro: string; story: string; tips: string[]; source: string; label: string };
const places: Place[] = [
    { id: 'islands', title: 'Hundred Islands', town: 'Alaminos City', category: 'Island escapes', image:'${BASE}/images/hundred.jpg', intro: 'A little island. A whole new perspective.', story: 'Discover the island-dotted waters of the Hundred Islands National Park in Alaminos. Limestone formations, quiet coves and sea views make this a distinctive part of Pangasinan’s natural heritage.', tips: ['Arrange your visit through the local tourism office at Lucap.', 'Bring drinking water, sun protection and a reusable bag.', 'Follow your boat operator’s safety instructions and leave marine life undisturbed.'], source: 'https://www.pangasinan.gov.ph/city-municipalities/alaminos-city/', label: 'Sea & discovery' },
    { id: 'lighthouse', title: 'Cape Bolinao Lighthouse', town: 'Bolinao', category: 'Heritage trails',image:'${BASE}/images/light.jpg', intro: 'Follow the coast. Find a story.', story: 'Above the coast of Patar, Cape Bolinao Lighthouse connects the landscape with the province’s maritime story. Take time to appreciate the landmark and the coastal communities around it.', tips: ['Confirm current access with the local tourism office.', 'Bring sun protection for the exposed grounds.', 'Respect barriers and signs; tower access should not be assumed.'], source: 'https://bolinaopangasinan.gov.ph/services/tourism-3/', label: 'History & horizons' },
    { id: 'springs', title: 'Balungao Hot Springs', town: 'Balungao', category: 'Nature retreats',image:'${BASE}/images/spring'.jpg, intro: 'Slow days, warm waters, greener views.', story: 'At the foot of Mount Balungao, hot and cold springs offer a different side of Pangasinan. Trade the coastline for an inland landscape and discover the town’s connection to its mountain and local traditions.', tips: ['Check operating hours and facilities directly before traveling.', 'Bring swimwear, a towel and a change of clothes.', 'Follow posted pool guidance and keep the surroundings clean.'], source: 'https://www.balungao.gov.ph/?page_id=595', label: 'Nature & renewal' }];
const categories = ['All destinations', 'Island escapes', 'Heritage trails', 'Nature retreats'];
export default function Home() {
    const [category, setCategory] = useState(categories[0]); const [saved, setSaved] = useState<string[]>([]); const [low, setLow] = useState(false); const [ready, setReady] = useState(false); const [active, setActive] = useState<Place | null>(null); const [planner, setPlanner] = useState(false); const [menu, setMenu] = useState(false); const [notice, setNotice] = useState(''); const dialog = useRef<HTMLDialogElement>(null); const [photoErrors, setPhotoErrors] = useState<string[]>([]);
    useEffect(() => { try { const a = JSON.parse(localStorage.getItem('pangasinan-trip') || '[]'); if (Array.isArray(a)) setSaved(a.filter((id: unknown) => typeof id === 'string' && places.some(p => p.id === id))); setLow(localStorage.getItem('pangasinan-low') === 'true' || Boolean((navigator as Navigator & { connection?: { saveData?: boolean } }).connection?.saveData)); } catch { } setReady(true); }, []);
    useEffect(() => { if (!ready) return; try { localStorage.setItem('pangasinan-trip', JSON.stringify(saved)); localStorage.setItem('pangasinan-low', String(low)); } catch { setNotice('Storage is unavailable. Your choices will last for this visit.'); } }, [saved, low, ready]);
    useEffect(() => { if (active || planner) { dialog.current?.showModal(); document.body.style.overflow = 'hidden'; } else { dialog.current?.close(); document.body.style.overflow = ''; } return () => { document.body.style.overflow = ''; }; }, [active, planner]);
    useEffect(() => { if (!notice) return; const t = setTimeout(() => setNotice(''), 4000); return () => clearTimeout(t) }, [notice]);
    function toggle(p: Place) { setSaved(s => s.includes(p.id) ? s.filter(x => x !== p.id) : [...s, p.id]); setNotice(saved.includes(p.id) ? `${p.title} removed from your trip` : `${p.title} saved to your trip`); }
    function close() { setActive(null); setPlanner(false) }
    function download() { const text = 'MY PANGASINAN TRIP\n\n' + places.filter(p => saved.includes(p.id)).map(p => `${p.title} — ${p.town}\n${p.story}\n${p.tips.map(t => '• ' + t).join('\n')}\nOfficial information: ${p.source}`).join('\n\n') + '\n\nConfirm rates, access and opening hours before departure. These destinations are spread across the province; plan transport and overnight stops separately.'; const u = URL.createObjectURL(new Blob([text], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = u; a.download = 'my-pangasinan-trip.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(u), 1000); }
    function photo(p: Place, hero = false) { return <div className={`photo ${hero ? 'hero-photo' : ''}`}>{ready && !low && !photoErrors.includes(p.id) ? <img src={p.image} alt={p.title + ' in ' + p.town} width={hero ? 1100 : 600} height={hero ? 1000 : 450} loading={hero ? 'eager' : 'lazy'} fetchPriority={hero ? 'high' : 'auto'} onError={() => setPhotoErrors(e => [...e, p.id])} /> : <div className="photo-fallback"><Compass size={48} /><span>{p.title}</span><small>{low ? 'Low-data mode · Photos paused' : 'Pangasinan, Philippines'}</small></div>}</div> }
    return <><a href="#main" className="skip">Skip to content</a><header><a className="brand" href="#"><span className="brand-symbol"><Waves size={26} /></span><span>Pangasinan<small>WANDER. CONNECT. DISCOVER.</small></span></a><nav aria-label="Main navigation" className={menu ? 'open' : ''}><a href="#destinations" onClick={() => setMenu(false)}>Discover</a><a href="#our-story" onClick={() => setMenu(false)}>Our story</a><button onClick={() => { setPlanner(true); setMenu(false) }}>My trip <span className="count">{saved.length}</span></button></nav><div className="header-actions"><button className={'data-toggle ' + (low ? 'enabled' : '')} aria-pressed={low} onClick={() => setLow(!low)} title="Pause photos to use less mobile data"><Signal size={16} /><span>Low data</span><span className="switch" /></button><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div></header>
        <main id="main"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span /> YOUR NEXT STORY STARTS HERE</div><h1>A place to<br />wander.<br /><em>A feeling to<br className="desktop-break" /> keep.</em></h1><p>Island mornings. Coastal stories. A warm welcome.<br className="desktop-break" /> Find your kind of wonder in Pangasinan.</p><a className="button primary" href="#destinations">Find your next escape <ArrowUpRight size={20} /></a><div className="hero-foot"><span className="mini-compass"><Compass size={25} /></span><span>Closer to nature.<br /><strong>Connected to our roots.</strong></span><span className="coordinates">16.01° N<br />120.34° E</span></div></div><div className="hero-visual">{photo(places[0], true)}<span className="vertical-caption">A DIFFERENT KIND OF GETAWAY</span><div className="postmark"><Sun size={24} /><span>A little closer<br />to paradise</span></div><div className="image-caption"><span><small><MapPin size={13} /> ALAMINOS CITY</small><strong>One hundred reasons<br />to fall in love.</strong></span><button aria-label="Explore Hundred Islands" onClick={() => setActive(places[0])}><ArrowUpRight /></button></div></div></section>
            <div className="ribbon"><span><Waves /> Coastlines worth the journey</span><span>✳</span><span><Landmark /> Stories that stay with you</span><span>✳</span><span><Leaf /> Travel gently. Discover deeply.</span></div>
            <section className="destinations section" id="destinations"><div className="section-heading"><div><div className="eyebrow">THREE PLACES. COUNTLESS POSSIBILITIES.</div><h2>Where will your<br /><em>curiosity take you?</em></h2></div><p>From sea-swept islands to quiet mountain escapes,<br className="desktop-break" /> there’s a corner of Pangasinan calling your name.</p></div><div className="filters" aria-label="Filter destinations">{categories.map((c, i) => <button key={c} aria-pressed={category === c} className={category === c ? 'selected' : ''} onClick={() => setCategory(c)}>{i === 0 ? <Compass size={17} /> : i === 1 ? <Waves size={17} /> : i === 2 ? <Landmark size={17} /> : <Mountain size={17} />} {c}</button>)}</div><div className="cards">{places.filter(p => category === categories[0] || category === p.category).map((p, i) => <article className="card" key={p.id}><div className="card-image"><button className="photo-button" aria-label={'Discover ' + p.title} onClick={() => setActive(p)}>{photo(p)}</button><span className="card-tag">{p.label}</span><button className={'save ' + (saved.includes(p.id) ? 'saved' : '')} aria-label={(saved.includes(p.id) ? 'Remove ' : 'Save ') + p.title} aria-pressed={saved.includes(p.id)} onClick={() => toggle(p)}><Heart size={19} fill={saved.includes(p.id) ? 'currentColor' : 'none'} /></button></div><div className="card-body"><small><MapPin size={13} />{p.town.toUpperCase()}</small><h3><button onClick={() => setActive(p)}>{p.title}</button></h3><p>{p.intro}</p><button className="text-link" onClick={() => setActive(p)}>Meet your next escape <ArrowUpRight size={18} /></button></div></article>)}</div><p className="results" aria-live="polite">{category === categories[0] ? 'Three signature destinations. One unforgettable province.' : `${places.filter(p => p.category === category).length} destination to discover`}</p></section>
            <section className="story section" id="our-story"><div className="story-intro"><div className="eyebrow">MORE THAN A PLACE ON THE MAP</div><h2>Come for the views.<br /><em>Stay for the stories.</em></h2><p>Pangasinan’s character lives in its coastlines, its inland towns, and the communities that call it home. Every visit is a chance to listen, learn, and leave with a deeper connection.</p><a href="https://www.pangasinan.gov.ph/" target="_blank" rel="noreferrer" className="text-link">Get to know Pangasinan <ArrowUpRight size={18} /></a></div><div className="values"><div><span>01</span><div><h3>Make it local.</h3><p>Choose local guides, try regional food, and make space for the stories people share.</p></div></div><div><span>02</span><div><h3>Leave only light footsteps.</h3><p>Bring reusables, respect wildlife, and take your waste home. Small choices protect extraordinary places.</p></div></div><div><span>03</span><div><h3>Take your time.</h3><p>These destinations span the province. Check local travel conditions and give each place room in your itinerary.</p></div></div></div></section>
            <section className="trip-banner"><div><span className="eyebrow">A LITTLE PLANNING. A LOT OF POSSIBILITY.</span><h2>Your next chapter<br />looks good from here.</h2></div><button className="button light" onClick={() => setPlanner(true)}>Open my trip <ArrowRight size={20} /></button></section></main>
        <footer><a className="brand" href="#"><span className="brand-symbol"><Waves size={25} /></span><span>Pangasinan<small>KEEP EXPLORING.</small></span></a><p>A concept travel guide inspired by Pangasinan.<br />Independent demonstration · Not an official government website.<br /><a href="/photo-credits.txt" target="_blank" rel="noreferrer">Photo credits &amp; licenses</a></p><a href="#main">Back to the sunshine ↑</a></footer>
        <dialog ref={dialog} onCancel={close} onClick={e => { if (e.target === dialog.current) close() }}><button className="close" aria-label="Close panel" onClick={close}><X /></button>{active ? <div className="detail">{photo(active)}<div className="detail-body"><div className="eyebrow">{active.town} · {active.category}</div><h2>{active.title}</h2><p>{active.story}</p><h3>Before you go</h3><ul>{active.tips.map(t => <li key={t}>{t}</li>)}</ul><p className="note">Check current rates, schedules and accessibility with the destination before your visit.</p><div className="detail-actions"><button className="button primary" onClick={() => toggle(active)}>{saved.includes(active.id) ? <Check size={18} /> : <Heart size={18} />} {saved.includes(active.id) ? 'Saved to my trip' : 'Save to my trip'}</button><a className="text-link" target="_blank" rel="noreferrer" href={active.source}>Official information <ArrowUpRight size={18} /></a></div></div></div> : planner ? <div className="planner"><div className="eyebrow">YOUR PERSONAL LITTLE GETAWAY</div><h2>My Pangasinan trip</h2><p>Save a little inspiration. Take it with you.</p>{saved.length ? <><div className="saved-list">{places.filter(p => saved.includes(p.id)).map(p => <div key={p.id}><MapPin /><div><h3>{p.title}</h3><span>{p.town}</span></div><button aria-label={'Remove ' + p.title} onClick={() => toggle(p)}><X size={18} /></button></div>)}</div><p className="note">This is your shortlist, not a timed route. Arrange transport and confirm opening hours with each destination.</p><button className="button primary" onClick={download}><Download size={18} /> Download trip notes</button></> : <div className="empty"><Compass size={48} /><h3>A good journey starts with a little curiosity.</h3><p>Tap the heart on a destination to save it here.</p><button className="button primary" onClick={() => { close(); document.getElementById('destinations')?.scrollIntoView() }}>Explore destinations <ChevronRight size={18} /></button></div>}<small className="privacy">Saved on this browser only. No account needed.</small></div> : null}</dialog><div role="status" className={'toast ' + (notice ? 'visible' : '')}>{notice}</div></>;
}
